version: 0.2
environment_variables:
  plaintext:
    TEMPLATE_FILES: |
      cloudformation/stackset/microservice.yaml
phases:
  pre_build:
    commands:
      - |
        for cfn_template in $TEMPLATE_FILES; do
          echo "Validating CloudFormation template file $cfn_template"
          aws cloudformation validate-template --template-body file://$cfn_template
        done

artifacts:
  files:
    - cloudformation/stackset/microservice.yaml