---
AWSTemplateFormatVersion: 2010-09-09

Resources:
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Body:
        OpenAPI specification
      Description: "A test API"
      Name: RestApi

