---
AWSTemplateFormatVersion: 2010-09-09

Resources:

  FilesBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicReadWrite
      BucketName: wixit-files-bucket

  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: "A test API"
      Name: RestApi

